### ISSUE TITLE
Latest build links offline

### ISSUE THREAD

**Issue by Keith94** [Fireboyd78/mm2hook#31]
The .zip files available from [appveyor](https://ci.appveyor.com/project/Fireboyd78/mm2hook/build/artifacts) say "not found".

Could you please add latest builds to: https://github.com/Fireboyd78/mm2hook/releases ? Thanks!

**Comment by Fireboyd78** [comment]
Looks like whatever was going on was a problem with AppVeyor itself. I just tried to download one of the files and it worked perfectly fine.
