### ISSUE TITLE
Widescreen support

### ISSUE THREAD

**Issue by Keith94** [Fireboyd78/mm2hook#32]
Does this project add widescreen resolution support to the game?

**Comment by Fireboyd78** [comment]
As long as your monitor supports it, any widescreen resolution should be supported. You do need mods to have dashboards fit the screen correctly, however.

If you experience any bugs or have any questions regarding this, please let us know!

**Comment by Keith94** [comment]
According to [WSGF](http://www.wsgf.org/dr/midtown-madness-2) the game has "Native support up to 1440x900. For higher resolutions, hex editing `gfxconf.dat` is required."

I'm wondering is there any alternative to hex editing? What mods are needed for the dashboards?

**Comment by Fireboyd78** [comment]
There is no hex editing required. Delete your old `gfxconf.dat` file and let the new auto-detect in MM2Hook generate a new one for you. As for dashboards, you'll need to find those mods yourself. I believe Revisited 5 does this for the default cars.

**Comment by Keith94** [comment]
Thanks!
