### ISSUE TITLE
Fix crash on exiting to windows while in multiplayer session

### ISSUE THREAD

**Issue by Fireboyd78** [Fireboyd78/mm2hook#33]
Caused by MM2Hook. I'm not sure what _exactly_ causes this, but apparently it's a thing.

**Comment by Deebz96** [comment]
Possibly related to Discord Rich Presence.

**Comment by Fireboyd78** [comment]
Fixed. 👍 

It wasn't related to Discord Rich Presence, but that did help me track down what was going wrong. I was shutting down the hook stuff too early, and since rich presence was still relying on network code, it was trying to write to the closed log file. I'm surprised it even worked the way I had it before...
