### ISSUE TITLE
Add Instant Replay to the pause menu

### ISSUE THREAD

**Issue by Fireboyd78** [Fireboyd78/mm2hook#35]
On pause menu, move the options button, quit to menu button, and quit to windows buttons down one space, and put the instant replay button between restart race and options.

**Comment by Deebz96** [comment]
To clarify, this button is already present on the pause menu with MM2Hook. However, the positioning is a little sloppy. All I’m looking for here is to position it better:

Restart Race
Instant Replay
Options
Quit to Main Menu
Exit to Windows
