### ISSUE TITLE
Implement AaronPatch features

### ISSUE THREAD

**Issue by Fireboyd78** [Fireboyd78/mm2hook#36]
## Core features
The following features should be implemented as part of MM2Hook as non-customizable enhancements.

- [x] Add **FixPOVFreezeHudState**. This fixes the hud vanishing if you switch to another camera while looking left/right/back in the dashboard view.
- [x] Add **ImpactCallbackSafeguard**. This fixes some crashes that randomly happen when you drop the gold in some areas of the city.
- [x] Add **MissingVehtypeSirenCrashFix**. Fixes the crash that occurs when you toggle the siren of a vehicle not listed in vehtypes. Lights come on, sound doesn't play.

## Optional features
These features can be toggled on or off, as they may create unwanted behavior for some users.

- [x] Add **AllowTrafficUseAllColors**. Allows traffic to use the last color in their list. Yes, they don't use those by default.
- [x] Add **FixNoAmbientSoundWithMusic**. This enables positional ambient sounds (like tube station sounds) when music is enabled.
- [x] Add **FixUIMusicAfterChatClose**. This fixes a bug that causes menu music to never stop playing after opening the chat box.
- [x] Add **IncreaseFerrySpeed**. They go 1 mph by default. Faster is nice.

**Comment by Deebz96** [comment]
- [x] To clarify, `FixUIMusicAfterChatClose` should also be an INI toggle. Believe it or not, I know someone who uses this bug because they like hearing menu music ingame.

**Comment by Deebz96** [comment]
- [x] Also, change music used in CnR from singleroam to singlerace. Not only is this more proper, but it also fixes a crash. Aaron did this in one of his patches.

**Comment by Deebz96** [comment]
- [x] Also fix the missing PVS crash.
