### ISSUE TITLE
Improvements to use of night textures and headlights/streetlights

### ISSUE THREAD

**Issue by Fireboyd78** [Fireboyd78/mm2hook#37]
Implement the following changes as configurable options:
- [x] Allow night textures to be used in the evening.
  - **TODO:** Make optional toggle
- [x] Use headlights in every condition except noon clear and noon cloudy, street lights in evening.
  - Partially addressed in commit e6013ec

**Comment by Fireboyd78** [comment]
Partially addressed in commit e6013ec.

**Comment by Deebz96** [comment]
This has been taken care of now, but I'm still hoping to have night textures turned into a per-lt file basis, rather than a global toggle for evening.

**Comment by Dummiesman** [comment]
Texture variants are now controlled in the td file
