### ISSUE TITLE
Improvements to parked car density

### ISSUE THREAD

**Issue by Fireboyd78** [Fireboyd78/mm2hook#38]
Allow users to toggle parked car density being linked to traffic car density (e.g. having little to no traffic should also result in parked cars appear less often).

**Comment by Deebz96** [comment]
This is high priority because of the sheer number of parked cars there are now in the SF garages, although it would be great for existing London paths too. It’s been requested before that I remove parked cars entirely from Revisited, so this is a happy medium in that area.

**Comment by Deebz96** [comment]
Make this tweak only apply to cruise mode. I just realized that the parked cars placed in some crash course events no longer show up, since there is no traffic in those.
