### ISSUE TITLE
Add water splash effect when sleeping with the fishes

### ISSUE THREAD

**Issue by Fireboyd78** [Fireboyd78/mm2hook#43]
Allow the ability to toggle a water splash effect that plays when a player drives into the ocean.

**Comment by Deebz96** [comment]
Just to clarify, it should play the aud/aud22/impacts/fountainsplash.22k.wav sound file immediately upon sleeping with the fishes. No visual effects are necessary.

**Comment by Dummiesman** [comment]
Update: Definitely possible via vehCarDamage. More research needs to be done into the impact structure though.

**Comment by Dummiesman** [comment]
@DatBrick Got the structure layout that I needed, now all that's left is implementing it. 

I'll paste it here for reference
```
struct vehDamageImpactInfo
{
  struct phCollider *pCollider;
  Vector3 dword4;
  Vector3 dword10;
  Vector3 dword1C;
  Vector3 dword28;
  float dword34;
  float dword38;
  uint32_t dword3C;
};

**Comment by Dummiesman** [comment]
Added in commit af5c3e025493e671b3ef8f977b24581fda8f6246
