### ISSUE TITLE
Fix positions for extra wheels

### ISSUE THREAD

**Issue by Fireboyd78** [Fireboyd78/mm2hook#46]
Make the `WHL4` and `WHL5` objects use the positions defined by the .mtx files instead of being automatic.

**Comment by Deebz96** [comment]
Note: MTX positions are used in the vehicle selection screen. However, after the city loads, they are automatically positioned at a set distance behind WHL2 and 3.

**Comment by Dummiesman** [comment]
The positions of these wheels are hardcoded to be +2 behind their respective pair. 

Example @ 0x4CE5B8
