### ISSUE TITLE
Implement fix for out-of-map freezes

### ISSUE THREAD

**Issue by Fireboyd78** [Fireboyd78/mm2hook#47]
Instead of having the player vehicle disappear when entering an invalid SDL block, simply respawn the player similar to what happens when falling under the map.

**Comment by Deebz96** [comment]
This should be an INI toggle. Believe it or not, we used to play games with this bug. See who could launch themselves higher out of map, stuff like that. :P

For normal gameplay though, this would be great.

**Comment by Dummiesman** [comment]
This feature is most likely complete, pending testing & bugfixes if needed

**Comment by Dummiesman** [comment]
- [x] Add gold drop
After this, I think this can be considered closed.

**Comment by Dummiesman** [comment]
Commit 205b1d3d70ed7ab1e6f18ebd9c675c3b5d923253 closes #47
