### ISSUE TITLE
Fix strange vehicle reflections in foggy weather

### ISSUE THREAD

**Issue by Fireboyd78** [Fireboyd78/mm2hook#48]
Vehicles appear to get brighter the further away the camera is, but suddenly go back to normal once a certain distance is reached. Either disable reflections entirely or make this look nicer.

**Comment by Deebz96** [comment]
Example of this bug: https://youtu.be/Eten-86oZJc

**Comment by Dummiesman** [comment]
I think this just may be a side effect of additive rendering + fog.

 Also reflections are disabled when the model is not rendering the H, hence why they seem to be "fixed" at a further distance.

**Comment by Dummiesman** [comment]
Fixed by disabling fog while the reflections get drawn, preventing the additive blending from mixing with the fog in the first place.
