### ISSUE TITLE
Fix bug with position of rain particles

### ISSUE THREAD

**Issue by Fireboyd78** [Fireboyd78/mm2hook#50]
Fix rain being centered on rear view mirror camera position when it’s turned on, rather than the main camera.

**Note:** I'm not entirely sure what this actually looks like, so clarification would be appreciated.

**Comment by Deebz96** [comment]
Here is an example of this bug: https://youtu.be/_2AmTfRPzSM

Notice how the rain follows the main camera, until the rear view mirror is enabled. Then it centers on the position of that camera.

Note: The weird look of the rain is intended, to better show this bug.

**Comment by Dummiesman** [comment]
MM2 only updates the asBirthRule of the particles, it doesn't move the particles themselves.

The normal order is
Main Camera Render -> Sets the camera matrix
Level PreDraw -> Updates particles, including drawing new ones and positioning them
Level Draw -> Sets the position of the particles to the camera matrix

This is fine, until the mirror comes into play and sets the order to
Main Camera Render -> Sets the camera matrix
Mirror cull -> Sets the camera matrix
Level Draw (called from cull) -> Sets the position of the particles to the camera matrix
Level PreDraw -> Updates particles, including drawing new ones and positioning them
Level Draw -> Sets the position of the particles to the camera matrix

We need to make a flag that makes it so the particles don't update position on the Mirror cull call of Level Draw.
