### ISSUE TITLE
Allow vehicles to use headlight/siren objects

### ISSUE THREAD

**Issue by Fireboyd78** [Fireboyd78/mm2hook#52]
Implement a feature that toggles the ability for vehicles to use the `HLIGHT` (headlight) and `SLIGHT` (siren light) objects, if present. Some models would require tweaks for these to be used effectively.

**Comment by Deebz96** [comment]
This is highly subjective of course. Something to possibly be addressed after everything else has been taken care of. I could use it to enhance how the default cars look with their lights on, although it could also cause issues with addon cars if they have these objects haphazardly placed.

**Comment by Deebz96** [comment]
Nevermind on this one.
