### ISSUE TITLE
Fix issues with paintjobs

### ISSUE THREAD

**Issue by Deebz96** [Fireboyd78/mm2hook#55]
- [ ] ~If possible, increase the character limit of the `Colors` field in .info files. It is currently at 100 characters, which is pretty restrictive.~ _Not feasible._

- [x] Fix a bug that causes gizmo objects to spawn inside of a vehicle if it has over 10 paintjobs, and an 11th or higher paintjob is selected: ![](https://cdn.discordapp.com/attachments/241631360370868224/435157654118072331/unknown.png)

**Comment by Fireboyd78** [comment]
Considering this finished since adding more room for paintjob names isn't exactly an "issue" -- it's also just not feasible or worth the effort needed.
