### ISSUE TITLE
Fix Slider Vanishing in Widescreen Resolutions

### ISSUE THREAD

**Issue by Deebz96** [Fireboyd78/mm2hook#60]
In the ingame options menu, if you are playing in a widescreen resolutions, the red slider bars will become invisible if you drag them too far to the right. This makes it very difficult to set things accurately.

**Comment by Deebz96** [comment]
Fixed by simply increasing the width of SLIDER_ACTL.tga from 500px to 1000px. No side effects, no mm2hook patch needed.

**Comment by 0x1F9F1** [comment]
For future reference there are 4 textures that need to be modified to completley fix it: SLIDER_ACTL, SLIDER_INACTL, SLIDER_ROACTL and SLIDER_ROINACTL.
ACTL is for the active/left part of the slider.
INACTL is for the inactive/right part of the slider.
RO is short for read-only, which is for the sliders you can't modify.
By default they are all 500px wide, so the slider goes invisible if more than 500px wide.

**Comment by Deebz96** [comment]
SLIDER_ACTL is the only one used in the ingame options menu, which is the only place I know of that has this bug. So extending that one should be enough.
