### ISSUE TITLE
Disable dashboard view if dashboard model is missing.

### ISSUE THREAD

**Issue by Deebz96** [Fireboyd78/mm2hook#65]
If the dashboard model is missing from a vehicle, disallow switching to the dashboard view. Similar to the missing hudmap fix, the button to switch to this view should do nothing.

Also automatically switch the dashboard view to another camera (maybe the bumper camera) if the dash view is selected on a vehicle without one. This is a failsafe to prevent the dash view being usable if your last used camera view was the dash, on another vehicle.

Alternatively: Simply enable the HUD in the dash view of a vehcle that is missing the dash model.

INI toggle: MissingDashboardFix

**Comment by ghost** [comment]
Maybe allowing a default dashboard for vehicles that don't have one seems a better idea.

**Comment by Wanted9811** [comment]
Fixed in commit befa9d2eb8611ee4f5815bfe0efb707d0641af48
