### ISSUE TITLE
Artifact unavailable due to lack of commits

### ISSUE THREAD

**Issue by SmallJoker** [Fireboyd78/mm2hook#68]
> Artifacts older than 6 months are automatically deleted. For more details see Artifacts retention policy. 

Source: https://ci.appveyor.com/project/Fireboyd78/mm2hook/build/artifacts

Compiling this project on Linux is quite annoying, thus: Would you please be so nice and provide a new release on GitHub? 
Thanks a lot; I'd love to play MM2 without these crashes.

**Comment by Fireboyd78** [comment]
Fixed - sorry about that!

**Comment by SmallJoker** [comment]
Thank you for providing the binaries for further 6 months.

I've got a follow-up question: How do I run the mm2hook? There's neither an executable nor instructions in the README.
