### ISSUE TITLE
Can't allocate more than 512MB in the heapsize

### ISSUE THREAD

**Issue by ghost** [Fireboyd78/mm2hook#69]
Attempting to allocate more than 512MB in the heapsize will result in an instant crash when attempting to start the game. No useful logs found.

**Comment by 0x1F9F1** [comment]
This isn't something that can really be fixed, since 512 MB is already a huge amount, and failing to allocate more is just the result of the OS not being able to find a large enough chunk of memory that is free, which is not something we can control.
