### ISSUE TITLE
[Feature Request] CPU Opponent Pursuit

### ISSUE THREAD

**Issue by ghost** [Fireboyd78/mm2hook#71]
Currently Cops do chase CPU opponents, however the condition for this to happen is either random (very low chance) or unknown.

Would be possible to always enable this behavior?

**Comment by Dummiesman** [comment]
This is configured in each race file. One of the numbers in the [Cops] line sets the random chance to pursue. A condition for this is also that they must be chasing you first.

**Comment by Wanted9811** [comment]
Forgot to tell, this was fixed 4 months ago in this commit 2ebacda78a1e2ca616969cdad5b7787f227efa86
