### ISSUE TITLE
Having MaxVehiclePaintJobs on mm2hook.ini causes problems

### ISSUE THREAD

**Issue by surrodox2001** [Fireboyd78/mm2hook#75]
Specifically, having that causes the models of AI cars to glitch and crashes the game with a heap overrun error when approaching Golden Gate Bridge on Golden Hour.

Proof:
![Midtown2 2020-03-29 21-41-30-17](https://user-images.githubusercontent.com/49476868/77851325-26d63280-720b-11ea-8c79-50671002b685.jpg)
![Midtown2 2020-03-29 21-46-00-90](https://user-images.githubusercontent.com/49476868/77851327-29d12300-720b-11ea-9126-d046cc2c3089.jpg)
![Midtown2 2020-03-29 21-46-01-18](https://user-images.githubusercontent.com/49476868/77851329-2b025000-720b-11ea-990f-55f3e69460f0.jpg)
![Midtown2 2020-03-29 21-46-01-84](https://user-images.githubusercontent.com/49476868/77851330-2b9ae680-720b-11ea-8c62-d9e5151b55cf.jpg)

Have any ideas why?

[mm2hook.ini](https://github.com/Fireboyd78/mm2hook/files/4399055/mm2hook.txt)

mm2hook.ini for reference.
(Game is unmodded except for XP patch and speedboot.)

**LONG OVERDUE UPDATE:**
The issue still happens on the latest version as of 22.4.2020.
The screens when the game crashed:
![Capture1](https://user-images.githubusercontent.com/49476868/79974283-9fa77200-84cb-11ea-93d6-c006e44bd306.JPG)
![crash1](https://user-images.githubusercontent.com/49476868/79974287-a209cc00-84cb-11ea-9f6f-453ee8e79981.jpg)

**Comment by Wanted9811** [comment]
The issue has been fixed!
