### ISSUE TITLE
[Feature Request] Better support for XInput controllers.

### ISSUE THREAD

**Issue by krittinen** [Fireboyd78/mm2hook#92]
[Currently the left and right triggers on Xbox 360 and Xbox One controllers are mapped to the same axis due to the way the XInput to DirectInput translation is done at the OS level](https://gaming.stackexchange.com/questions/62027/does-the-xbox-windows-controller-work-with-directinput-games)

This prevents the usage of the right trigger as throttle and left trigger as brake and viceversa.

**Comment by Fireboyd78** [comment]
There are no plans to implement XInput support into MM2Hook at this time.
